apiVersion: v1
kind: Service
metadata:
  name: mod-check-bot
spec:
  selector:
    app: mod-check-bot
  ports:
    - protocol: TCP
      port: 50505
      targetPort: 6060
      nodePort: 31110
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-check-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mod-check-bot
  template:
    metadata:
      labels:
        app: mod-check-bot
    spec:
      containers:
        - name: app
          image: modcheck/bot:1.0.0
          ports:
            - containerPort: 6060
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/modCheck
          imagePullPolicy: Always
